\LoadClass{article}
\RequirePackage{amsthm}
\RequirePackage{amsmath}
\RequirePackage{amssymb}
\RequirePackage{indentfirst}
\RequirePackage{booktabs}
\RequirePackage{multicol}
\RequirePackage{multirow}
\RequirePackage{linegoal}
\RequirePackage{graphicx}
\RequirePackage{fancyvrb}
\RequirePackage{abstract}
\RequirePackage{hologo}
\RequirePackage{enumerate}
\RequirePackage{geometry}
\geometry{a4paper,scale=0.9}
\RequirePackage{url}
\RequirePackage[UTF8]{ctex}
\RequirePackage{graphicx}
\RequirePackage{subfigure} 
\RequirePackage{appendix}
\RequirePackage{float}
\newtheorem{example}{例}[section]
\newtheorem{theorem}{定理}[section]
\newtheorem{definition}{定义}[section]
\newtheorem{property}{性质}[section]
\newtheorem{lemma}{引理}[section]
\newtheorem{proposition}{推论}[section]
\newtheorem{corollary}{推论}[section]
\newtheorem{algorithm}{算法}[section]
\renewcommand*{\proofname}{\normalfont\bfseries 证明}

\RequirePackage{xcolor}
\definecolor{winered}{rgb}{0.5,0,0}
\RequirePackage{hyperref}
\hypersetup{
  pdfborder={0 0 0},
  colorlinks=true,
  linkcolor={winered},
  urlcolor={winered},
  filecolor={winered},
  citecolor={winered},
  linktoc=all,
}
% \RequirePackage{hyperref}
% \hypersetup{
%             colorlinks,
%             linkcolor=winered,
%             anchorcolor=winered,
%             citecolor=winered
%             }

% \begin{figure}[H]
% 	\centering
% 	\includegraphics[width=0.6\textwidth]{figure/aaa.png}
% 	\caption{Scatter Plot Example \label{fig:scatter}}
% \end{figure}